name: Push API to Master
on:
  push:
    branches: master
    paths:
      - "src/api/**"
      - "src/lambda-helpers.ts"
      - ".github/workflows/master_api.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  CLERK_INSTANCE_ID: ins_1oXZdmHyu1Lej3hCAgZjG8yJVV4
  CLOUDFRONT_ARN: ${{ secrets.CLOUDFRONT_ARN }}
  CONVERTKIT_API_TOKEN: ${{ secrets.CONVERTKIT_API_TOKEN }}
  API_URL: https://api.roamjs.com
  DIAHOOK_SECRET: ${{ secrets.DIAHOOK_SECRET }}
  ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
  FLOSS_API_URL: https://api.davidvargas.me
  FLOSS_TOKEN: ${{ secrets.FLOSS_TOKEN }}
  DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
  DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }} 
  FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
  FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }} 
  GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
  GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  IFRAMELY_API_KEY: ${{ secrets.IFRAMELY_API_KEY }}
  LAMBDA_ROLE: ${{ secrets.LAMBDA_ROLE }}
  MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
  ROAM_CLIENT_API_KEY: ${{ secrets.ROAM_CLIENT_API_KEY }}
  ROAM_CLIENT_API_TOKEN: ${{ secrets.ROAM_CLIENT_API_TOKEN }}
  SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
  SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }} 

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: install
        run: npm install
      - name: Build
        run: npm run build:api
      - name: Upload
        run: |
          for filename in out/*.js; do
              LAMBDA=$(basename "$filename" .js)
              zip -jq $LAMBDA.zip ./out/$LAMBDA.js
              MODIFIED=$(aws lambda update-function-code --function-name "roam-js-extensions_${LAMBDA}" --publish --zip-file "fileb://${LAMBDA}.zip" --query "LastModified" --output text)  
              rm $LAMBDA.zip
              echo "Function $LAMBDA successfully updated at $MODIFIED"
          done
